// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function Button(Props) {
  var text = Props.text;
  var className = Props.className;
  var handleClick = Props.handleClick;
  return React.createElement("button", {
              className: className,
              onClick: handleClick
            }, text);
}

var make = Button;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
