// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./Button.bs.js";

function s(str) {
  return str;
}

function reducer(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return state - 1 | 0;
    } else {
      return state + 1 | 0;
    }
  } else {
    return action._0;
  }
}

function Counter(Props) {
  var initialCount = Props.initialCount;
  var match = React.useReducer(reducer, initialCount);
  var dispatch = match[1];
  var count = match[0];
  var countColor = count > 0 ? "bg-green-400" : (
      count < 0 ? "bg-red-400" : "bg-yellow-400"
    );
  return React.createElement("div", {
              className: "text-center mt-24 max-w-4xl mx-auto"
            }, React.createElement("p", {
                  className: countColor + " mb-8 py-4 text-4xl text-center"
                }, "Count is  " + String(count)), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement(Button.make, {
                      text: "Increment",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-green-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Increment */0);
                        })
                    }), React.createElement(Button.make, {
                      text: "Decrement",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-red-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Decrement */1);
                        })
                    }), React.createElement(Button.make, {
                      text: "Reset",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-yellow-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(dispatch, /* Reset */{
                                      _0: initialCount
                                    });
                        })
                    })));
}

var make = Counter;

export {
  s ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
