// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./Button.bs.js";

function s(prim) {
  return prim;
}

function Counter(Props) {
  var initialCount = Props.initialCount;
  var match = React.useState(function () {
        return initialCount;
      });
  var setCount = match[1];
  var count = match[0];
  var countColor = count > 0 ? "bg-green-400" : (
      count < 0 ? "bg-red-400" : "bg-yellow-400"
    );
  return React.createElement("div", {
              className: "text-center mt-24 max-w-4xl mx-auto"
            }, React.createElement("p", {
                  className: countColor + " mb-8 py-4 text-4xl text-center"
                }, "Count is  " + String(count)), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement(Button.make, {
                      text: "Increment",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-green-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (x) {
                                        return x + 1 | 0;
                                      }));
                        })
                    }), React.createElement(Button.make, {
                      text: "Decrement",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-red-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (x) {
                                        return x - 1 | 0;
                                      }));
                        })
                    }), React.createElement(Button.make, {
                      text: "Reset",
                      className: "border py-2 px-3 bg-gray-200 hover:bg-yellow-500 mr-2",
                      handleClick: (function (_mouseEvt) {
                          return Curry._1(setCount, (function (_x) {
                                        return initialCount;
                                      }));
                        })
                    })));
}

var make = Counter;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
