// Generated by ReScript, PLEASE EDIT WITH CARE


function make(text) {
  return {
          id: new Date().getTime(),
          text: text
        };
}

function id(t) {
  return t.id;
}

function text(t) {
  return t.text;
}

var LogEntry = {
  make: make,
  id: id,
  text: text
};

export {
  LogEntry ,
  
}
/* No side effect */
