// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LogEntry from "./LogEntry.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(str) {
  return str;
}

function LogsViewer$LogItem(Props) {
  var text = Props.text;
  return React.createElement("p", undefined, text);
}

var LogItem = {
  make: LogsViewer$LogItem
};

function LogsViewer(Props) {
  var logs = Props.logs;
  var logItems = Belt_Array.map(logs, (function (log) {
          return React.createElement(LogsViewer$LogItem, {
                      text: LogEntry.LogEntry.text(log),
                      key: String(LogEntry.LogEntry.id(log))
                    });
        }));
  return React.createElement("div", {
              className: "h-36 overflow-y-scroll border bg-gray-200 text-sm py-2 px-4"
            }, logItems);
}

var make = LogsViewer;

export {
  s ,
  LogItem ,
  make ,
  
}
/* react Not a pure module */
